---
title: "Bestselling Audio Books"
author: "Soo Chee Kiong, Ricky (17083991)"
date: "December 5th, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

**Shinyapps - [https://rickysoo.shinyapps.io/audiobooks](https://rickysoo.shinyapps.io/audiobooks)**

Data source: [Audible.com](https://www.audible.com/adblbestsellers) (5th December 2020)


```{r main, message=FALSE}
library(shiny)
library(shinythemes)
library(MASS)
library(dplyr)

ui <- fluidPage(
  theme = shinytheme('superhero'),
  
  titlePanel('Bestselling Audio Books'),
  hr(),
  h3('Choose the number of audio books to show'),

  sliderInput(
    inputId = 'Number',
    label = 'Select from 2 to 100:',
    min = 2,
    max = 100,
    value = 20,
    width = '100%'
  ),
  tabsetPanel(
    tabPanel('Books', tableOutput(outputId = 'books')),
    tabPanel('Length', plotOutput(outputId = 'length')),
    tabPanel('Year', plotOutput(outputId = 'year')),
    tabPanel('Ratings', plotOutput(outputId = 'ratings')),
    tabPanel('Stars', plotOutput(outputId = 'stars')),
    tabPanel('Prices', plotOutput(outputId = 'price')),
    tabPanel('Summary', verbatimTextOutput(outputId = 'summary'))
  )
)

server<- function(input, output) {
  load_df <- reactive({
    csv <- 'https://raw.githubusercontent.com/rickysoo/top_audiobooks/main/audiobooks-20201205.csv'
    
    df <- read.csv(csv) %>%
      mutate(
        Title = paste0('<a href="', URL, '" target="_blank">', Title, '</a>'),
        Length = Length / 60,
        Year = substr(Release, 1, 4)
      ) %>%
      select(-Subtitle, -Release, -URL)
    
    return(df)
  })

  output$books <- renderTable(
    load_df() %>% head(input$Number),
    bordered = TRUE,
    striped = TRUE,
    hover = TRUE,
    sanitize.text.function = function(x) x
  )

  output$length <- renderPlot({
    x <- load_df()[['Length']] %>% head(input$Number) %>% na.omit()

    hist.scott(x, prob = FALSE,
      col = '#75AADB',
      xlab = 'Hours',
      main = 'Lengths of Audio Books')
  })
  
  output$year <- renderPlot({
    x <- load_df()[['Year']] %>% head(input$Number)

    barplot(table(x), 
      col = '#75AADB', 
      xlab = 'Release Year',
      main = 'Release Year of Audio Books')
  })
  
  output$ratings <- renderPlot({
    x <- load_df()[['Ratings']] %>% head(input$Number) %>% na.omit()

    hist.scott(x, prob = FALSE,
      col = '#75AADB',
      xlab = 'Number of Ratings',
      main = 'Number of Ratings Received')
  })
  
  output$stars <- renderPlot({
    x <- load_df()[['Stars']] %>% head(input$Number) %>% na.omit()

    barplot(table(x), 
      col = '#75AADB',
      xlab = 'Number of Stars (out of 5 stars)',
      main = 'Number of Stars Received')
  })
  
  output$price <- renderPlot({
    x <- load_df()[['Price']] %>% head(input$Number) %>% na.omit()

    hist.scott(x, prob = FALSE,
      col = '#75AADB',
      xlab = 'Retail Price (US$)',
      main = 'Retail Prices of Audio Books')
  })
  
  output$summary <- renderPrint(
    load_df() %>% 
      head(input$Number) %>%
      select(Length, Stars, Ratings, Price) %>%
      summary()
  )
}

shinyApp(ui = ui, server = server)
```
